### ISSUE TITLE
odak

### ISSUE THREAD

**Issue by kaanaksit** [wbierbower/awesome-physics#4]
Thank you for putting this list together. May I kindly suggest my library named `Odak` to be listed for optics?

https://github.com/kunguz/odak

Thank you for considering.

**Comment by wbierbower** [comment]
Hi @kunguz, absolutely.   I think it can go under "Optics" between "lightpipes" and "opticspy" -- do you agree?

And do you want to open the pull request?   If not, I can add it

**Comment by kaanaksit** [comment]
Thanks! I have forked your repository, added `odak` under `Optics` between `lightpipes` and `opticspy` as suggested. I have also initiated a pull request #5  as suggested . I can't link the pull request to this repository as you are the owner of the repository, which I believe can be done by clicking on `Linked pull requests` on the right hand side in this issue window.

**Comment by wbierbower** [comment]
Thanks @kunguz!
